### ISSUE TITLE
Bug fix and improvement

### ISSUE THREAD

**Issue by farooq13** [Rachit74/fago#1]
i experience some ``issues`` when i try to post is this app, the problem is that **no field to add a community** user must choose from the drop down list of issues available and also there is no any community to choose from. I have a solution to this problem and i want to make some improvement to this project.

**Comment by farooq13** [comment]
let me give it a try

**Comment by Rachit74** [comment]
> i experience some ``issues`` when i try to post is this app, the problem is that **no field to add a community** user must choose from the drop down list of issues available and also there is no any community to choose from. I have a solution to this problem and i want to make some improvement to this project.

To post under a community user must be part of that community, communities that the user has created or joined will show up in the user menu.
You are welcome to make improvement

**Comment by farooq13** [comment]
That sounds cool. it is ok. Can you give an overview of all the features of the project?

**Comment by Rachit74** [comment]
> That sounds cool. it is ok. Can you give an overview of all the features of the project?

Sure, it's a very basic reddit clone, users can register and create communities and other users can join those communities to create posts under them, There is also a "Manage Community" page for the community owner which for now is only used to kick members out of community, though I will work more on it and I am thinking of adding an Notification system (I implemented it but It was not very good, so i removed it), The comments can be threaded like reddit and the users can edit their profile with a bio and profile picture.
There are alot of things that I will work on in future, currently I am writing rest api with [drf](https://www.django-rest-framework.org/) for fago.

**Comment by farooq13** [comment]
ok wonderful. Can you assign the notification feature to me, i am ready for it.

**Comment by Rachit74** [comment]
> ok wonderful. Can you assign the notification feature to me, i am ready for it.

Sure dude go ahead

**Comment by farooq13** [comment]
Good

**Comment by Rachit74** [comment]
@farooq13 i've pushed some changes to the main branch and the deployment too, fetch the updates before you start working!

**Comment by farooq13** [comment]
alright!

**Comment by Rachit74** [comment]
@farooq13 have you started working on the notification system? I am also thinking of making a lot of changes to the project.

**Comment by farooq13** [comment]
i have done with the Notification system, now i am trying to add like and dislike feature

**Comment by Rachit74** [comment]
> i have done with the Notification system, now i am trying to add like and dislike feature

great, did you push it to git? if it is working all fine than you can open a pull request.

**Comment by Rachit74** [comment]
@farooq13 Merged your pr and now on deployment, there was some issue with the db so all of the data was deleted, I basically had to redeploy the app but it works!

**Comment by farooq13** [comment]
Good job.
